language: java

jdk:
  - oraclejdk8

after_success:
  - test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && ./travis/publish_to_bintray.sh

branches:
  only:
    - master

env:
  global:
  - secure:
  - secure: 